repos:
  # Black: format code
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  # Mypy: check types
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2   # pick latest stable
    hooks:
      - id: mypy
        additional_dependencies: []

  # Pytest: run tests
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
