NUMBER_OF_COUPONS_ARGS_SHORT_OPTION = "-n"
NUMBER_OF_COUPONS_ARGS_LONG_OPTION = "--number_of_coupons"
NUMBER_OF_COUPONS_ARGS_OPTIONS = ", ".join(
    [NUMBER_OF_COUPONS_ARGS_SHORT_OPTION, NUMBER_OF_COUPONS_ARGS_LONG_OPTION]
)
LENGTH_OF_COUPON_ARGS_SHORT_OPTION = "-l"
LENGTH_OF_COUPON_ARGS_LONG_OPTION = "--length_of_coupon"
LENGTH_OF_COUPON_ARGS_OPTIONS = ", ".join(
    [LENGTH_OF_COUPON_ARGS_SHORT_OPTION, LENGTH_OF_COUPON_ARGS_LONG_OPTION]
)
COUPON_PREFIX_ARGS_SHORT_OPTION = "-p"
COUPON_PREFIX_ARGS_LONG_OPTION = "--prefix"
COUPON_PREFIX_ARGS_OPTIONS = ", ".join(
    [COUPON_PREFIX_ARGS_SHORT_OPTION, COUPON_PREFIX_ARGS_LONG_OPTION]
)
COUPON_SUFFIX_ARGS_SHORT_OPTION = "-s"
COUPON_SUFFIX_ARGS_LONG_OPTION = "--suffix"
COUPON_SUFFIX_ARGS_OPTIONS = ", ".join(
    [COUPON_SUFFIX_ARGS_SHORT_OPTION, COUPON_SUFFIX_ARGS_LONG_OPTION]
)
FILE_ARGS_SHORT_OPTION = "-f"
FILE_ARGS_LONG_OPTION = "--file"
FILE_ARGS_OPTIONS = ", ".join([FILE_ARGS_SHORT_OPTION, FILE_ARGS_LONG_OPTION])

MIN_NUMBER_OF_COUPONS = 1
MAX_NUMBER_OF_COUPONS = 1000000
DEFAULT_NUMBER_OF_COUPONS = 1
MIN_LENGTH_OF_COUPON = 4
MAX_LENGTH_OF_COUPON = 16
DEFAULT_LENGTH_OF_COUPON = 5
MAX_LENGTH_OF_PREFIX = 16
MAX_LENGTH_OF_SUFFIX = 16
ALLOWED_CHARACTERS_FOR_PREFIX = "[A-Z0-9]"
ALLOWED_CHARACTERS_FOR_SUFFIX = "[A-Z0-9]"
CHARACTER_SET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
OUTPUT_DIR = "output"
OUTPUT_FILENAME = "coupons.txt"
ALLOWED_CHARACTERS_FOR_FILENAME = "[a-zA-Z0-9-_]"
ALLOWED_FILE_EXTENSION_FOR_FILENAME = "(txt|csv)"
